CREATE TABLE SYM_PB_GOALS_DESC
(
  DASHBOARD_DESC_ID NUMBER(5) NOT NULL,
  Description       CLOB,
  PROJECT_ID        NUMBER(5) NOT NULL,
  CREATION_DATE     DATE,
  LAST_UPDATE_DATE  DATE,
  CREATED_BY        VARCHAR2(50),
  LAST_UPDATED_BY   VARCHAR2(50),
  LAST_UPDATE_LOGIN VARCHAR2(50),
  CONSTRAINT dashboard_desc_pk PRIMARY KEY (DASHBOARD_DESC_ID),
  CONSTRAINT fk_PROJECT_ID
  FOREIGN KEY (PROJECT_ID)
  REFERENCES SYM_PB_PROJECTS (PROJECT_ID)
)
/

CREATE TABLE SYM_PB_USER_FEEDBACK
(
  TITLE_ID          NUMBER(5) NOT NULL,
  TITLE             VARCHAR2(50),
  TYPE              VARCHAR2(15),
  CREATED_BY        VARCHAR2(25),
  STATUS            VARCHAR2(15),
  PROJECT_ID        NUMBER(5) NOT NULL,
  CREATION_DATE     DATE,
  LAST_UPDATE_DATE  DATE,
  CREATED_BY        VARCHAR2(25),
  LAST_UPDATED_BY   VARCHAR2(25),
  LAST_UPDATE_LOGIN VARCHAR2(25),
  CONSTRAINT title_id_pk PRIMARY KEY (TITLE_ID)
)
/

CREATE TABLE SYM_PB_FEEDBACK_STATUS
(
  TITLE_STATUS_ID       NUMBER(5) NOT NULL,
  TITLE_ID              NUMBER(5) NOT NULL,
  NAME                  VARCHAR2(25),
  COMPLETION_PERCENTAGE NUMBER(5),
  DUE_DATE              DATE,
  STATUS                VARCHAR2(10),
  PROJECT_ID            NUMBER(5) NOT NULL,
  CREATION_DATE         DATE,
  LAST_UPDATE_DATE      DATE,
  CREATED_BY            VARCHAR2(25),
  LAST_UPDATED_BY       VARCHAR2(25),
  LAST_UPDATE_LOGIN     VARCHAR2(25),
  CONSTRAINT TITLE_STATUS_ID_PK PRIMARY KEY (TITLE_STATUS_ID)
)
/

CREATE TABLE SYM_PB_USERS
(
  USER_ID             NUMBER(5) NOT NULL,
  USER_FULL_NAME      VARCHAR2(25),
  FIRST_NAME          VARCHAR2(25),
  LAST_NAME           VARCHAR2(25),
  TYPE                VARCHAR2(25),
  ROLE                VARCHAR2(25),
  EMAIL_ID            VARCHAR2(50),
  SURVEY              NUMBER(10),
  TASK                NUMBER(10),
  PROGRESS_PERCENTAGE NUMBER(5),
  DEFECTS             NUMBER(5),
  DEPARTMENT_ID       NUMBER(5),
  USER_PHOTOGRAPH     BLOB,
  TASK_ID             NUMBER(5),
  PROJECT_ID          NUMBER(5) NOT NULL,
  CREATION_DATE       DATE,
  LAST_UPDATE_DATE    DATE,
  CREATED_BY          VARCHAR2(25),
  LAST_UPDATED_BY     VARCHAR2(25),
  LAST_UPDATE_LOGIN   VARCHAR2(25),
  CONSTRAINT USER_ID_PK PRIMARY KEY (USER_ID)
)
/


CREATE TABLE SYM_PB_ROLES
(
  ROLE_ID           NUMBER(5) NOT NULL,
  ROLE_NAME         VARCHAR2(25),
  CREATION_DATE     DATE,
  LAST_UPDATE_DATE  DATE,
  CREATED_BY        VARCHAR2(25),
  LAST_UPDATED_BY   VARCHAR2(25),
  LAST_UPDATE_LOGIN VARCHAR2(25),
  PROJECT_ID        NUMBER(5) NOT NULL,
  CONSTRAINT ROLE_ID_PK PRIMARY KE Y (ROLE_ID)
)
/

CREATE TABLE SYM_PB_DOCUMENT
(
  DOCUMENT_ID        NUMBER(5) NOT NULL,
  NAME               VARCHAR2(25),
  INSTRUCTIONS_TITLE VARCHAR2(25),
  INSTRUCTIONS_DESC  VARCHAR2(50),
  ATTACH_DOCUMENT    BLOB,
  PROJECT_ID         NUMBER(5) NOT NULL,
  CREATION_DATE      DATE,
  LAST_UPDATE_DATE   DATE,
  CREATED_BY         VARCHAR2(25),
  LAST_UPDATED_BY    VARCHAR2(25),
  LAST_UPDATE_LOGIN  VARCHAR2(25),
  CONSTRAINT DOCUMENT_ID_PK PRIMARY KEY (DOCUMENT_ID)
)/

CREATE TABLE SYM_PB_PROJECTS
(
  PROJECT_ID         NUMBER(5) NOT NULL,
  PROJECT_NAME       VARCHAR2(25),
  DESCRIPTION        VARCHAR2(250),
  INSTRUCTIONS       VARCHAR2(25),
  DEPARTMENT_NAME    VARCHAR2(25),
  PRODUCT_NAME       VARCHAR2(25),
  PRODUCT_TYPE       VARCHAR2(25),
  MANAGER            VARCHAR2(25),
  NUMBER_OF_MACHINES NUMBER(5),
  DUE_ON             DATE,
  PRODUCT_VERSION    NUMBER(10),
  START_DATE         DATE,
  END_DATE           DATE,
  GOAL               VARCHAR2(250),
  RELEASE_NOTES      VARCHAR2(100),
  PROJECT_TYPE       VARCHAR2(10),
  ISPUBLIC           VARCHAR2(1),
  CREATION_DATE      DATE,
  LAST_UPDATE_DATE   DATE,
  CREATED_BY         VARCHAR2(25),
  LAST_UPDATED_BY    VARCHAR2(25),
  LAST_UPDATE_LOGIN  VARCHAR2(25),
  PROJECT_AGREEMENT  CLOB,
  PROJECT_STATUS     VARCHAR2(15),
  AGREEMENT_STATUS   VARCHAR2(1),
  CONSTRAINT PROJECT_ID_PK PRIMARY KEY (PROJECT_ID)
)
/

CREATE TABLE SYM_PB_TASKS
(
  TASK_ID           NUMBER(5)  NOT NULL,
  NAME              VARCHAR2(150),
  DESCRIPTION       VARCHAR2(2000),
  --PRIORITY VARCHAR2(50), deleted and added to the defects table
  ATTACHMENTS       BLOB,
  --ADD_NOTE VARCHAR2(150), it can be removed from this table
  ADD_SURVEYS       VARCHAR2(25),
  --CREATED_ON DATE, removed from table
  --LAST_MODIFIED SYSDATE, removed from table
  DUE_DATE          DATE,
  STATUS            VARCHAR2(15),
  PROJECT_ID        NUMBER(10) NOT NULL,
  ACTIVE            VARCHAR2(1),
  CREATION_DATE     DATE,
  LAST_UPDATE_DATE  DATE,
  CREATED_BY        VARCHAR2(25),
  LAST_UPDATED_BY   VARCHAR2(25),
  LAST_UPDATE_LOGIN VARCHAR2(25),
  --DETAILS CLOB,
  CONSTRAINT TASK_ID_PK PRIMARY KEY (TASK_ID)
)
/

CREATE TABLE SYM_PB_SURVEYS
(
  SURVEY_ID         NUMBER(5) NOT NULL,
  NAME              VARCHAR2(25),
  --CREATED_ON DATE, removed
  LAST_MODIFIED     DATE,
  ACTIVE            VARCHAR2(1),
  --USER_ID NUMBER(20),
  PROJECT_ID        NUMBER(5) NOT NULL,
  CREATION_DATE     DATE,
  LAST_UPDATE_DATE  DATE,
  CREATED_BY        VARCHAR2(25),
  LAST_UPDATED_BY   VARCHAR2(25),
  LAST_UPDATE_LOGIN VARCHAR2(25),
  CONSTRAINT SURVEY_ID_PK PRIMARY KEY (SURVEY_ID)
)/


CREATE TABLE SYM_PB_DEFECTS
(
  DEFECT_ID         NUMBER(5) NOT NULL,
  TITLE             VARCHAR2(25),
  TYPE              VARCHAR2(25),
  PRIORITY          VARCHAR2(25),
  STATUS            VARCHAR2(25),
  DESCRIPTION       VARCHAR2(100),
  ASSOCIATED_WITH   VARCHAR2(25),
  --ATTACH CLOB,
  USER_ID           NUMBER(5),
  PROJECT_ID        NUMBER(5) NOT NULL,
  CREATION_DATE     DATE,
  LAST_UPDATE_DATE  DATE,
  CREATED_BY        VARCHAR2(25),
  LAST_UPDATED_BY   VARCHAR2(25),
  LAST_UPDATE_LOGIN VARCHAR2(25),
  CONSTRAINT DEFECT_ID_PK PRIMARY KEY (DEFECT_ID)
)
/

CREATE TABLE SYM_PB_EMAIL_TEMPLATES
(
  EMAIL_TEMPLATE_ID NUMBER(5) NOT NULL,
  NAME              VARCHAR2(25),
  ACTIVE            VARCHAR2(1),
  EMAIL_DESCRIPTION VARCHAR2(2000),
  PROJECT_ID        NUMBER(5) NOT NULL,
  CREATION_DATE     DATE,
  LAST_UPDATE_DATE  DATE,
  CREATED_BY        VARCHAR2(25),
  LAST_UPDATED_BY   VARCHAR2(25),
  LAST_UPDATE_LOGIN VARCHAR2(25),
  CONSTRAINT EMAIL_TEMPLATE_ID_PK PRIMARY KEY (EMAIL_TEMPLATE_ID)
)
/

CREATE TABLE SYM_PB_RESOURCES
(
  RESOURCE_ID             NUMBER(5) NOT NULL,
  APPLICATION_URL         SYS.URIType,
  FIELD_NAME              VARCHAR2(25),
  PROJECT_GUIDE           VARCHAR2(250),
  LINKS                   SYS.URIType,
  SOFTWARE_BUILD          SYS.URIType,
  DISTRIBUTED_LICENCE_KEY VARCHAR2(10),
  PROJECT_ID              NUMBER(5) NOT NULL,
  CREATION_DATE           DATE,
  LAST_UPDATE_DATE        DATE,
  CREATED_BY              VARCHAR2(25),
  LAST_UPDATED_BY         VARCHAR2(25),
  LAST_UPDATE_LOGIN       VARCHAR2(25),
  CONSTRAINT RESOURCE_ID_ID_PK PRIMARY KEY (RESOURCE_ID)
)
/

CREATE TABLE SYM_PB_FORUMS
(
  FORUM_ID         NUMBER(5) NOT NULL,
  NAME             SYS.URIType,
  POSTS            NUMBER(5),
  UNREAD           NUMBER(5),
  CREATED_BY       VARCHAR2(25),
  CREATION_DATE    DATE,
  LAST_POSTED_DATE DATE,
  PROJECT_ID       NUMBER(5),
  CONSTRAINT FORUM_ID_PK PRIMARY KEY (FORUM_ID)
)
/

CREATE TABLE SYM_PB_TOPICS
(
  TOPIC_ID         NUMBER(5) NOT NULL,
  TOPIC_NAME       VARCHAR2(50),
  POSTS            NUMBER(5),
  UNREAD           NUMBER(5),
  CREATED_BY       VARCHAR2(25),
  CREATION_DATE    DATE,
  LAST_POSTED_DATE DATE,
  FORUM_ID         NUMBER(5),
  CONSTRAINT TOPIC_ID_PK PRIMARY KEY (TOPIC_ID)
)
/

CREATE TABLE SYM_PB_FORUM_QNS_AND_ANS
(
  QUESTION_ID      NUMBER(5) NOT NULL,
  QUESTION_TITLE   VARCHAR2(50),
  QUESTIONED_BY    VARCHAR2(30),
  QUESTION         VARCHAR2(150),
  ANSWERED_BY      VARCHAR2(30),
  ANSWER           VARCHAR2(250),
  TOPIC_ID         NUMBER(5),
  CREATED_BY       VARCHAR2(25),
  CREATION_DATE    DATE,
  LAST_POSTED_DATE DATE,
  CONSTRAINT QUESTION_ID_PK PRIMARY KEY (QUESTION_ID)
)
/


CREATE TABLE SYM_PB_APPL_AGREEMENT
(
  APPL_AGREEMENT_ID NUMBER(5) NOT NULL,
  AGREEMENT         CLOB,
  STATUS            VARCHAR2(15),
  PROJECT_ID        NUMBER(5) NOT NULL,
  CREATION_DATE     DATE,
  LAST_UPDATE_DATE  DATE,
  CREATED_BY        VARCHAR2(25),
  LAST_UPDATED_BY   VARCHAR2(25),
  LAST_UPDATE_LOGIN VARCHAR2(25),
  CONSTRAINT APPL_AGREEMENT_ID_PK PRIMARY KEY (APPL_AGREEMENT_ID)
)
/

CREATE TABLE SYM_PB_ACTION_ITEMS
(
  ACTION_ITEM_ID    NUMBER(5) NOT NULL,
  NAME              VARCHAR2(50),
  TYPE              VARCHAR2(25),
  DUE_DATE          DATE,
  STATUS            VARCHAR2(15),
  PROJECT_ID        NUMBER(5) NOT NULL,
  CREATION_DATE     DATE,
  LAST_UPDATE_DATE  DATE,
  CREATED_BY        VARCHAR2(25),
  LAST_UPDATED_BY   VARCHAR2(25),
  LAST_UPDATE_LOGIN VARCHAR2(25),
  CONSTRAINT ACTION_ITEM_ID_PK PRIMARY KEY (ACTION_ITEM_ID)
)
/

