INSERT INTO SYSTEM.SYM_PB_DEFECTS (DEFECT_ID,
                                   TITLE,
                                   TYPE,
                                   PRIORITY,
                                   STATUS,
                                   DESCRIPTION,
                                   ASSOCIATED_WITH,
                                   USER_ID,
                                   PROJECT_ID,
                                   CREATION_DATE,
                                   LAST_UPDATE_DATE,
                                   CREATED_BY,
                                   LAST_UPDATED_BY,
                                   LAST_UPDATE_LOGIN)
VALUES (1,
        'Bug_Fix',
        'Bug_Fix',
        'Normal',
        'Active',
        null,
        null,
        1,
        1,
        TO_DATE('2018-11-01 16:17:07', 'YYYY-MM-DD HH24:MI:SS'),
        TO_DATE('2018-11-01 16:17:00', 'YYYY-MM-DD HH24:MI:SS'),
        'Anshul Mohil',
        'Anshul Mohil',
        'Anshul Mohil');


INSERT INTO SYSTEM.SYM_PB_DEFECTS (DEFECT_ID,
                                   TITLE,
                                   TYPE,
                                   PRIORITY,
                                   STATUS,
                                   DESCRIPTION,
                                   ASSOCIATED_WITH,
                                   USER_ID,
                                   PROJECT_ID,
                                   CREATION_DATE,
                                   LAST_UPDATE_DATE,
                                   CREATED_BY,
                                   LAST_UPDATED_BY,
                                   LAST_UPDATE_LOGIN)
VALUES (2,
        'Enhancement',
        'Enhancement',
        'Normal',
        'Active',
        null,
        null,
        2,
        1,
        TO_DATE('2018-11-01 16:18:54', 'YYYY-MM-DD HH24:MI:SS'),
        TO_DATE('2018-11-01 16:19:00', 'YYYY-MM-DD HH24:MI:SS'),
        'Uday s',
        'Uday s',
        'Uday s');