INSERT INTO SYSTEM.SYM_PB_PROJECTS (PROJECT_ID,
                                    PROJECT_NAME,
                                    DESCRIPTION,
                                    INSTRUCTIONS,
                                    DEPARTMENT_NAME,
                                    PRODUCT_NAME,
                                    PRODUCT_TYPE,
                                    MANAGER,
                                    NUMBER_OF_MACHINES,
                                    DUE_ON,
                                    PRODUCT_VERSION,
                                    START_DATE,
                                    END_DATE,
                                    GOAL,
                                    RELEASE_NOTES,
                                    PROJECT_TYPE,
                                    PUBLIC_OR_NOT,
                                    CREATION_DATE,
                                    LAST_UPDATE_DATE,
                                    CREATED_BY,
                                    LAST_UPDATED_BY,
                                    LAST_UPDATE_LOGIN,
                                    PROJECT_AGREEMENT,
                                    PROJECT_STATUS,
                                    AGREEMENT_STATUS)
VALUES (1,
        'Sym beta1',
        'bla bla bla ...',
        'none',
        'Cloud_Eng1',
        'Symentic_cloud1',
        null,
        'Naresh',
        19,
        null,
        1,
        null,
        TO_DATE('2018-11-29 15:29:34', 'YYYY-MM-DD HH24:MI:SS'),
        '100',
        'bla bla bla ..',
        null,
        'Y',
        null,
        null,
        'Naresh',
        'Naresh',
        null,
        'bla bla bla ...',
        null,
        null);

INSERT INTO SYSTEM.SYM_PB_PROJECTS (PROJECT_ID,
                                    PROJECT_NAME,
                                    DESCRIPTION,
                                    INSTRUCTIONS,
                                    DEPARTMENT_NAME,
                                    PRODUCT_NAME,
                                    PRODUCT_TYPE,
                                    MANAGER,
                                    NUMBER_OF_MACHINES,
                                    DUE_ON,
                                    PRODUCT_VERSION,
                                    START_DATE,
                                    END_DATE,
                                    GOAL,
                                    RELEASE_NOTES,
                                    PROJECT_TYPE,
                                    PUBLIC_OR_NOT,
                                    CREATION_DATE,
                                    LAST_UPDATE_DATE,
                                    CREATED_BY,
                                    LAST_UPDATED_BY,
                                    LAST_UPDATE_LOGIN,
                                    PROJECT_AGREEMENT,
                                    PROJECT_STATUS,
                                    AGREEMENT_STATUS)
VALUES (2,
        'Sym beta2',
        'bla bla bla ...',
        'none',
        'Cloud_Eng2',
        'Symentic_cloud2',
        null,
        'Naresh',
        11,
        null,
        1,
        null,
        TO_DATE('2018-11-29 15:29:34', 'YYYY-MM-DD HH24:MI:SS'),
        '100',
        'bla bla bla ..',
        null,
        'Y',
        null,
        null,
        'Naresh',
        'Naresh',
        null,
        'bla bla bla ...',
        null,
        null);


INSERT INTO SYSTEM.SYM_PB_PROJECTS (PROJECT_ID,
                                    PROJECT_NAME,
                                    DESCRIPTION,
                                    INSTRUCTIONS,
                                    DEPARTMENT_NAME,
                                    PRODUCT_NAME,
                                    PRODUCT_TYPE,
                                    MANAGER,
                                    NUMBER_OF_MACHINES,
                                    DUE_ON,
                                    PRODUCT_VERSION,
                                    START_DATE,
                                    END_DATE,
                                    GOAL,
                                    RELEASE_NOTES,
                                    PROJECT_TYPE,
                                    PUBLIC_OR_NOT,
                                    CREATION_DATE,
                                    LAST_UPDATE_DATE,
                                    CREATED_BY,
                                    LAST_UPDATED_BY,
                                    LAST_UPDATE_LOGIN,
                                    PROJECT_AGREEMENT,
                                    PROJECT_STATUS,
                                    AGREEMENT_STATUS)
VALUES (3,
        'Sym beta3',
        'bla bla bla ...',
        'none',
        'Cloud_Eng3',
        'Symentic_cloud3',
        null,
        'Naresh',
        18,
        null,
        1,
        null,
        TO_DATE('2018-11-29 15:29:34', 'YYYY-MM-DD HH24:MI:SS'),
        '100',
        'bla bla bla ..',
        null,
        'Y',
        null,
        null,
        'Naresh',
        'Naresh',
        null,
        'bla bla bla ...',
        null,
        null);


INSERT INTO SYSTEM.SYM_PB_PROJECTS (PROJECT_ID,
                                    PROJECT_NAME,
                                    DESCRIPTION,
                                    INSTRUCTIONS,
                                    DEPARTMENT_NAME,
                                    PRODUCT_NAME,
                                    PRODUCT_TYPE,
                                    MANAGER,
                                    NUMBER_OF_MACHINES,
                                    DUE_ON,
                                    PRODUCT_VERSION,
                                    START_DATE,
                                    END_DATE,
                                    GOAL,
                                    RELEASE_NOTES,
                                    PROJECT_TYPE,
                                    PUBLIC_OR_NOT,
                                    CREATION_DATE,
                                    LAST_UPDATE_DATE,
                                    CREATED_BY,
                                    LAST_UPDATED_BY,
                                    LAST_UPDATE_LOGIN,
                                    PROJECT_AGREEMENT,
                                    PROJECT_STATUS,
                                    AGREEMENT_STATUS)
VALUES (4,
        'Sym beta4',
        'bla bla bla ...',
        'none',
        'Cloud_Eng4',
        'Symentic_cloud4',
        null,
        'Naresh',
        8,
        null,
        1,
        null,
        TO_DATE('2018-11-29 15:29:34', 'YYYY-MM-DD HH24:MI:SS'),
        '100',
        'bla bla bla ..',
        null,
        'Y',
        null,
        null,
        'Naresh',
        'Naresh',
        null,
        'bla bla bla ...',
        null,
        null);


INSERT INTO SYSTEM.SYM_PB_PROJECTS (PROJECT_ID,
                                    PROJECT_NAME,
                                    DESCRIPTION,
                                    INSTRUCTIONS,
                                    DEPARTMENT_NAME,
                                    PRODUCT_NAME,
                                    PRODUCT_TYPE,
                                    MANAGER,
                                    NUMBER_OF_MACHINES,
                                    DUE_ON,
                                    PRODUCT_VERSION,
                                    START_DATE,
                                    END_DATE,
                                    GOAL,
                                    RELEASE_NOTES,
                                    PROJECT_TYPE,
                                    PUBLIC_OR_NOT,
                                    CREATION_DATE,
                                    LAST_UPDATE_DATE,
                                    CREATED_BY,
                                    LAST_UPDATED_BY,
                                    LAST_UPDATE_LOGIN,
                                    PROJECT_AGREEMENT,
                                    PROJECT_STATUS,
                                    AGREEMENT_STATUS)
VALUES (5,
        'Sym beta5',
        'bla bla bla ...',
        'none',
        'Cloud_Eng5',
        'Symentic_cloud5',
        null,
        'Naresh',
        2,
        null,
        1,
        null,
        TO_DATE('2018-11-29 15:29:34', 'YYYY-MM-DD HH24:MI:SS'),
        '100',
        'bla bla bla ..',
        null,
        'Y',
        null,
        null,
        'Naresh',
        'Naresh',
        null,
        'bla bla bla ...',
        null,
        null);


INSERT INTO SYSTEM.SYM_PB_PROJECTS (PROJECT_ID,
                                    PROJECT_NAME,
                                    DESCRIPTION,
                                    INSTRUCTIONS,
                                    DEPARTMENT_NAME,
                                    PRODUCT_NAME,
                                    PRODUCT_TYPE,
                                    MANAGER,
                                    NUMBER_OF_MACHINES,
                                    DUE_ON,
                                    PRODUCT_VERSION,
                                    START_DATE,
                                    END_DATE,
                                    GOAL,
                                    RELEASE_NOTES,
                                    PROJECT_TYPE,
                                    PUBLIC_OR_NOT,
                                    CREATION_DATE,
                                    LAST_UPDATE_DATE,
                                    CREATED_BY,
                                    LAST_UPDATED_BY,
                                    LAST_UPDATE_LOGIN,
                                    PROJECT_AGREEMENT,
                                    PROJECT_STATUS,
                                    AGREEMENT_STATUS)
VALUES (6,
        'Sym beta6',
        'bla bla bla ...',
        'none',
        'Cloud_Eng6',
        'Symentic_cloud6',
        null,
        'Naresh',
        7,
        null,
        1,
        null,
        TO_DATE('2018-11-29 15:29:34', 'YYYY-MM-DD HH24:MI:SS'),
        '100',
        'bla bla bla ..',
        null,
        'Y',
        null,
        null,
        'Naresh',
        'Naresh',
        null,
        'bla bla bla ...',
        null,
        null);


INSERT INTO SYSTEM.SYM_PB_PROJECTS (PROJECT_ID,
                                    PROJECT_NAME,
                                    DESCRIPTION,
                                    INSTRUCTIONS,
                                    DEPARTMENT_NAME,
                                    PRODUCT_NAME,
                                    PRODUCT_TYPE,
                                    MANAGER,
                                    NUMBER_OF_MACHINES,
                                    DUE_ON,
                                    PRODUCT_VERSION,
                                    START_DATE,
                                    END_DATE,
                                    GOAL,
                                    RELEASE_NOTES,
                                    PROJECT_TYPE,
                                    PUBLIC_OR_NOT,
                                    CREATION_DATE,
                                    LAST_UPDATE_DATE,
                                    CREATED_BY,
                                    LAST_UPDATED_BY,
                                    LAST_UPDATE_LOGIN,
                                    PROJECT_AGREEMENT,
                                    PROJECT_STATUS,
                                    AGREEMENT_STATUS)
VALUES (7,
        'Sym beta7',
        'bla bla bla ...',
        'none',
        'Cloud_Eng7',
        'Symentic_cloud7',
        null,
        'Naresh',
        14,
        null,
        1,
        null,
        TO_DATE('2018-11-29 15:29:34', 'YYYY-MM-DD HH24:MI:SS'),
        '100',
        'bla bla bla ..',
        null,
        'Y',
        null,
        null,
        'Naresh',
        'Naresh',
        null,
        'bla bla bla ...',
        null,
        null);