INSERT INTO SYSTEM.SYM_PB_USERS (USER_ID,
                                 USER_FULL_NAME,
                                 FIRST_NAME,
                                 LAST_NAME,
                                 TYPE,
                                 ROLE,
                                 EMAIL_ID,
                                 SURVEY,
                                 TASK,
                                 PROGRESS_PERCENTAGE,
                                 DEFECTS,
                                 DEPARTMENT_ID,
                                 USER_PHOTOGRAPH,
                                 TASK_ID,
                                 PROJECT_ID,
                                 CREATION_DATE,
                                 LAST_UPDATE_DATE,
                                 CREATED_BY,
                                 LAST_UPDATED_BY,
                                 LAST_UPDATE_LOGIN)
VALUES (1,
        'Anshul Mohil',
        'Anshul',
        'Mohil',
        'Admin',
        'Admin',
        'anshul@gmail.com',
        null,
        null,
        40,
        2,
        1,
        null,
        1,
        1,
        TO_DATE('2018-11-01 15:56:22', 'YYYY-MM-DD HH24:MI:SS'),
        TO_DATE('2018-11-01 15:56:28', 'YYYY-MM-DD HH24:MI:SS'),
        'Anshul Mohil',
        'Anshul Mohil',
        'Anshul Mohil');

INSERT INTO SYSTEM.SYM_PB_USERS (USER_ID,
                                 USER_FULL_NAME,
                                 FIRST_NAME,
                                 LAST_NAME,
                                 TYPE,
                                 ROLE,
                                 EMAIL_ID,
                                 SURVEY,
                                 TASK,
                                 PROGRESS_PERCENTAGE,
                                 DEFECTS,
                                 DEPARTMENT_ID,
                                 USER_PHOTOGRAPH,
                                 TASK_ID,
                                 PROJECT_ID,
                                 CREATION_DATE,
                                 LAST_UPDATE_DATE,
                                 CREATED_BY,
                                 LAST_UPDATED_BY,
                                 LAST_UPDATE_LOGIN)
VALUES (2,
        'uday s',
        'uday',
        's',
        'Admin',
        'Admin',
        'uday@gmail.com',
        null,
        null,
        40,
        2,
        1,
        null,
        1,
        1,
        TO_DATE('2018-11-01 15:56:22', 'YYYY-MM-DD HH24:MI:SS'),
        TO_DATE('2018-11-01 15:56:28', 'YYYY-MM-DD HH24:MI:SS'),
        'uday s',
        'uday s',
        'uday s');

-- INSERT INTO SYSTEM.SYM_PB_USERS (
-- USER_ID, USER_FULL_NAME, FIRST_NAME, LAST_NAME, TYPE, ROLE, EMAIL_ID,
-- SURVEY, TASK, PROGRESS_PERCENTAGE, DEFECTS, DEPARTMENT_ID, USER_PHOTOGRAPH,
-- TASK_ID, PROJECT_ID, CREATION_DATE, LAST_UPDATE_DATE, CREATED_BY,
-- LAST_UPDATED_BY, LAST_UPDATE_LOGIN)
-- VALUES (
-- 1, 'Anshul Mohil', 'Anshul', 'Mohil', 'Admin', 'Admin', 'anshul@gmail.com',
-- null, null, 40, 2, 1, null, 1, 1, TO_DATE('2018-11-01 15:56:22', 'YYYY-MM-DD HH24:MI:SS'),
-- TO_DATE('2018-11-01 15:56:28', 'YYYY-MM-DD HH24:MI:SS'), 'Anshul Mohil',
-- 'Anshul Mohil', 'Anshul Mohil'
-- );
--
-- INSERT INTO SYSTEM.SYM_PB_USERS (
-- USER_ID, USER_FULL_NAME, FIRST_NAME, LAST_NAME, TYPE, ROLE, EMAIL_ID,
-- SURVEY, TASK, PROGRESS_PERCENTAGE, DEFECTS, DEPARTMENT_ID, USER_PHOTOGRAPH,
-- TASK_ID, PROJECT_ID, CREATION_DATE, LAST_UPDATE_DATE, CREATED_BY,
-- LAST_UPDATED_BY, LAST_UPDATE_LOGIN)
-- VALUES (
-- 1, 'Anshul Mohil', 'Anshul', 'Mohil', 'Admin', 'Admin', 'anshul@gmail.com',
-- null, null, 40, 2, 1, null, 1, 1, TO_DATE('2018-11-01 15:56:22', 'YYYY-MM-DD HH24:MI:SS'),
-- TO_DATE('2018-11-01 15:56:28', 'YYYY-MM-DD HH24:MI:SS'), 'Anshul Mohil',
-- 'Anshul Mohil', 'Anshul Mohil'
-- );