INSERT INTO SYSTEM.SYM_PB_ACTION_ITEMS (ACTION_ITEM_ID,
                                        NAME,
                                        TYPE,
                                        DUE_DATE,
                                        STATUS,
                                        PROJECT_ID,
                                        CREATION_DATE,
                                        LAST_UPDATE_DATE,
                                        CREATED_BY,
                                        LAST_UPDATED_BY,
                                        LAST_UPDATE_LOGIN)
VALUES (1,
        'Defect_1.023',
        'Critical',
        TO_DATE('2018-11-30 16:07:33', 'YYYY-MM-DD HH24:MI:SS'),
        'ACTIVE',
        1,
        TO_DATE('2018-11-01 16:21:18', 'YYYY-MM-DD HH24:MI:SS'),
        TO_DATE('2018-11-01 16:21:19', 'YYYY-MM-DD HH24:MI:SS'),
        'Anshul Mohil',
        'Anshul Mohil',
        'Anshul Mohil');
INSERT INTO SYSTEM.SYM_PB_ACTION_ITEMS (ACTION_ITEM_ID,
                                        NAME,
                                        TYPE,
                                        DUE_DATE,
                                        STATUS,
                                        PROJECT_ID,
                                        CREATION_DATE,
                                        LAST_UPDATE_DATE,
                                        CREATED_BY,
                                        LAST_UPDATED_BY,
                                        LAST_UPDATE_LOGIN)
VALUES (2,
        'Defect_2.023',
        'Normal',
        TO_DATE('2018-11-30 16:07:33', 'YYYY-MM-DD HH24:MI:SS'),
        'ACTIVE',
        1,
        TO_DATE('2018-11-01 16:21:22', 'YYYY-MM-DD HH24:MI:SS'),
        TO_DATE('2018-11-01 16:21:23', 'YYYY-MM-DD HH24:MI:SS'),
        'Uday S',
        'Uday S',
        'Uday S');
INSERT INTO SYSTEM.SYM_PB_ACTION_ITEMS (ACTION_ITEM_ID,
                                        NAME,
                                        TYPE,
                                        DUE_DATE,
                                        STATUS,
                                        PROJECT_ID,
                                        CREATION_DATE,
                                        LAST_UPDATE_DATE,
                                        CREATED_BY,
                                        LAST_UPDATED_BY,
                                        LAST_UPDATE_LOGIN)
VALUES (3,
        'Enhancement_1.289',
        'Normal',
        TO_DATE('2018-11-01 16:21:01', 'YYYY-MM-DD HH24:MI:SS'),
        'ACTIVE',
        2,
        TO_DATE('2018-11-01 16:21:11', 'YYYY-MM-DD HH24:MI:SS'),
        TO_DATE('2018-11-01 16:21:16', 'YYYY-MM-DD HH24:MI:SS'),
        'Anshul Mohil',
        'Anshul Mohil',
        'Anshul Mohil');
INSERT INTO SYSTEM.SYM_PB_ACTION_ITEMS (ACTION_ITEM_ID,
                                        NAME,
                                        TYPE,
                                        DUE_DATE,
                                        STATUS,
                                        PROJECT_ID,
                                        CREATION_DATE,
                                        LAST_UPDATE_DATE,
                                        CREATED_BY,
                                        LAST_UPDATED_BY,
                                        LAST_UPDATE_LOGIN)
VALUES (4,
        'Enhancement',
        'Normal',
        TO_DATE('2018-11-03 10:23:41', 'YYYY-MM-DD HH24:MI:SS'),
        'INACTIVE',
        1,
        TO_DATE('2018-11-03 10:23:44', 'YYYY-MM-DD HH24:MI:SS'),
        TO_DATE('2018-11-03 10:23:47', 'YYYY-MM-DD HH24:MI:SS'),
        'Bharat',
        'Bharat',
        'Bharat');