SELECT
       ( SELECT COUNT(*) FROM SYM_PB_USERS WHERE PROJECT_ID = ?1)
AS USER_COUNT,
       ( SELECT COUNT(*) FROM SYM_PB_ACTION_ITEMS WHERE PROJECT_ID = ?1 AND STATUS = ?2)
AS ACTION_COUNT,
       ( SELECT COUNT(*) FROM SYM_PB_DEFECTS WHERE PROJECT_ID = ?1)
AS DEFECT_COUNT,
       ( SELECT COUNT(*) FROM SYM_PB_FORUMS WHERE PROJECT_ID = ?1)
AS FORUM_COUNT
       FROM DUAL;

SELECT DEPARTMENT_NAME, PRODUCT_NAME, PRODUCT_TYPE, START_DATE, END_DATE, DESCRIPTION FROM SYM_PB_PROJECTS WHERE PROJECT_ID = ?1;




SELECT (SELECT COUNT(*) FROM SYM_PB_USERS WHERE PROJECT_ID = 1) AS USER_COUNT,
( SELECT COUNT(*) FROM SYM_PB_ACTION_ITEMS WHERE PROJECT_ID = 1 ) AS ACTION_COUNT,
       ( SELECT COUNT(*) FROM SYM_PB_DEFECTS WHERE PROJECT_ID = 1) AS DEFECT_COUNT,
       ( SELECT COUNT(*) FROM SYM_PB_FORUMS WHERE PROJECT_ID = 1) AS FORUM_COUNT FROM DUAL;